// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf40m7Vo2WwjP4uxEcAd-rOBhwk-wIOgM',
    appId: '1:376696690673:web:6b3ee0064ba70ff6abd650',
    messagingSenderId: '376696690673',
    projectId: 'cloud-firebase-demo-2270c',
    authDomain: 'cloud-firebase-demo-2270c.firebaseapp.com',
    storageBucket: 'cloud-firebase-demo-2270c.appspot.com',
    measurementId: 'G-8G38TFGG8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgji70GchlU51rVTAXe_M1PilWyARyT8',
    appId: '1:376696690673:android:a559e41076351f95abd650',
    messagingSenderId: '376696690673',
    projectId: 'cloud-firebase-demo-2270c',
    storageBucket: 'cloud-firebase-demo-2270c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15HgfhZupa3hz8_C7929gcpmprZJf6cg',
    appId: '1:376696690673:ios:7870dc8bf598088eabd650',
    messagingSenderId: '376696690673',
    projectId: 'cloud-firebase-demo-2270c',
    storageBucket: 'cloud-firebase-demo-2270c.appspot.com',
    iosBundleId: 'com.example.cloudDatabaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15HgfhZupa3hz8_C7929gcpmprZJf6cg',
    appId: '1:376696690673:ios:7870dc8bf598088eabd650',
    messagingSenderId: '376696690673',
    projectId: 'cloud-firebase-demo-2270c',
    storageBucket: 'cloud-firebase-demo-2270c.appspot.com',
    iosBundleId: 'com.example.cloudDatabaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf40m7Vo2WwjP4uxEcAd-rOBhwk-wIOgM',
    appId: '1:376696690673:web:0c034ff61973e13fabd650',
    messagingSenderId: '376696690673',
    projectId: 'cloud-firebase-demo-2270c',
    authDomain: 'cloud-firebase-demo-2270c.firebaseapp.com',
    storageBucket: 'cloud-firebase-demo-2270c.appspot.com',
    measurementId: 'G-NSG1LC6FMQ',
  );
}
